n1 = int(input('Digite um numero: '))
print('Analizando o numero {}, Conseguimos dizer que:'.format(n1))
print('O dobro dele é: {}'.format(n1 * 2))
print('O triplo é: {}'.format(n1 * 3))
print('E a raiz quadrada é: {:.2f}'.format(n1 ** (1 / 2)))
