N1 = int(input('digite um numero: '))
print('analizando o numero {} conseguimos dizer que:'.format(N1))
print('o dobro dele é {}'.format(N1*2))
print('o triplo é {}'.format(N1*3))
print('e a raiz quadrada é {;.2f}'.format(N1**(1/2)))
