a1 = input('digite algo: ')
print('o tipo primitivo do que foi digitado é {}'.format(type(a1)))
print('é alfabetico: {}'.format(a1.isalpha()))
print('é alfanumerico: {}'.format(a1.isalnum()))
print('é numerico: {}'.format(a1.isnumeric()))
print('esta escrito so com maiusculo: {}'.format(a1.isupper()))
print('esta escrito so com minusculos: {}'.format(a1.islower()))
print('esta escrito so com espaços: {}'.format(a1.isspace()))
print('esta captalizada: {}'.format(a1.istitle()))
