A = float(input('altura da parede: '))
L = float(input('largura da parede: '))
AREA = (A * L)
TINTA = (AREA / 2)
print('Sua parede tem dimenção de {}x{} e sua area é de {}m².'.format(A, L, AREA))
print('Para pintar toda a parede sera necessario {:.2f} litros de tinta.'.format(TINTA))